/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TTreeIdRouteImport } from './routes/t.$treeId'
import { Route as AuthDashboardRouteImport } from './routes/_auth.dashboard'
import { Route as AuthTreesTreeIdRouteImport } from './routes/_auth.trees.$treeId'
import { Route as AuthTreesTreeIdSettingsRouteImport } from './routes/_auth.trees.$treeId.settings'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TTreeIdRoute = TTreeIdRouteImport.update({
  id: '/t/$treeId',
  path: '/t/$treeId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTreesTreeIdRoute = AuthTreesTreeIdRouteImport.update({
  id: '/trees/$treeId',
  path: '/trees/$treeId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTreesTreeIdSettingsRoute = AuthTreesTreeIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthTreesTreeIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthDashboardRoute
  '/t/$treeId': typeof TTreeIdRoute
  '/trees/$treeId': typeof AuthTreesTreeIdRouteWithChildren
  '/trees/$treeId/settings': typeof AuthTreesTreeIdSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthDashboardRoute
  '/t/$treeId': typeof TTreeIdRoute
  '/trees/$treeId': typeof AuthTreesTreeIdRouteWithChildren
  '/trees/$treeId/settings': typeof AuthTreesTreeIdSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/t/$treeId': typeof TTreeIdRoute
  '/_auth/trees/$treeId': typeof AuthTreesTreeIdRouteWithChildren
  '/_auth/trees/$treeId/settings': typeof AuthTreesTreeIdSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/t/$treeId'
    | '/trees/$treeId'
    | '/trees/$treeId/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/t/$treeId'
    | '/trees/$treeId'
    | '/trees/$treeId/settings'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/_auth/dashboard'
    | '/t/$treeId'
    | '/_auth/trees/$treeId'
    | '/_auth/trees/$treeId/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  TTreeIdRoute: typeof TTreeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$treeId': {
      id: '/t/$treeId'
      path: '/t/$treeId'
      fullPath: '/t/$treeId'
      preLoaderRoute: typeof TTreeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/trees/$treeId': {
      id: '/_auth/trees/$treeId'
      path: '/trees/$treeId'
      fullPath: '/trees/$treeId'
      preLoaderRoute: typeof AuthTreesTreeIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/trees/$treeId/settings': {
      id: '/_auth/trees/$treeId/settings'
      path: '/settings'
      fullPath: '/trees/$treeId/settings'
      preLoaderRoute: typeof AuthTreesTreeIdSettingsRouteImport
      parentRoute: typeof AuthTreesTreeIdRoute
    }
  }
}

interface AuthTreesTreeIdRouteChildren {
  AuthTreesTreeIdSettingsRoute: typeof AuthTreesTreeIdSettingsRoute
}

const AuthTreesTreeIdRouteChildren: AuthTreesTreeIdRouteChildren = {
  AuthTreesTreeIdSettingsRoute: AuthTreesTreeIdSettingsRoute,
}

const AuthTreesTreeIdRouteWithChildren = AuthTreesTreeIdRoute._addFileChildren(
  AuthTreesTreeIdRouteChildren,
)

interface AuthRouteChildren {
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthTreesTreeIdRoute: typeof AuthTreesTreeIdRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthDashboardRoute: AuthDashboardRoute,
  AuthTreesTreeIdRoute: AuthTreesTreeIdRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  TTreeIdRoute: TTreeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
